name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do repositorio
      uses: actions/checkout@v4.1.1
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{secrets.DOCKER_HUB_USER}}
        password: ${{secrets.DOCKER_HUB_SECRET}}
    - name: Build and push Docker images
      uses: docker/build-push-action@v5.0.0
      with:
        context: ./kube-news/src
        file: ./kube-news/src/Dockerfile
        push: true
        tags: |
          fabioreis2023/kube-news:${{ github.run_number }}
          fabioreis2023/kube-news:latest

  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
    - name: Checkout do repositorio
      uses: actions/checkout@v4.1.1
    - name: Configuração da credencial da AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{secrets.AWS_ACCESS_ID}}
        aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        aws-region: us-east-1 
    - name: Configurar o kubeConfig
      run: aws eks update-kubeconfig --name eks-imersao --region us-east-1
    - name: Deploy to Kubernetes cluster
      uses: Azure/k8s-deploy@v4.9
      with:
        manifests: |
          ./kube-news/k8s/deployment.yaml
        images: |
          fabioreis2023/kube-news:${{ github.run_number }}
          
      
  
