name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Efetuar o login no docker hub
      run: echo "executar o docker login"
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{secrets.DOCKER_HUB_USER}}
        password: ${{secrets.DOCKER_HUB_SECRET}}
    - name: Construir a imagem de container
      run: echo "executar o docker build"
    - name: Enviar a imagem para o docker registry
      run: echo "executar o docker push"

  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
    - name: Autenticar na AWS
      run: echo "autenticar na AWS"
    - name: Configurar o kubeConfig
      run: echo "configurar kubeConfig"
    - name: Aplicar o deploy
      run: echo "executar o kubectl apply"
      
  
